language: r
sudo: false
cache: packages
r_packages:
- covr
- drat
after_success:
- R -q -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: nj/d2lJND2/gJWXIu7afa501gWn3FLBzgKf2q/sExngZ2wnIgPmJ/viQT0fAxQ5s01VLnaGdN2aggZCzU3Gh0fdR+kD0opFBo/qnZbGaFNmE95daxKAm5RY1kPNygB/AFr/5m+HXaCZbaq9Ysk6SA5hy7DaLx967a5sqT3xuVRY=
