language: r
sudo: required
r_packages:
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: KGdWqq7NrikIkM/qchAtliqthtq+xAQVl1eHEm8KTJjEdB+B5ZeQZ9xgFhVwEgWq6zScxeflk1L1XxNL1WJysO7fzDaeSdLoDzyDNGZT8aXYNvmOF1oivVRipKE6gf3OVm4kUEyspMeIYRQBxEfGOeAdzWl7JJjXNQPhC4X080A=
